### ISSUE TITLE
Unable to get it working

### ISSUE THREAD

**Issue by AceTheWiz** [imyelo/docsify-plantuml#3] opened 2018-04-05 18:26 UTC
My setup
- Win 7 64bit
- Nodejs v8.8.1

What I have done.
- Included the docsify-plantuml.min.js script in index.html
- Include the @startuml ... @enduml code as per the example.
- Run docsify serve

The other md text appears but not the diagram. Did I miss something ?
Also checked in Chrome dev tools there are no errors.

Help would be appreciated.

**Comment by AceTheWiz** [comment] 2018-04-05 20:13
Wow ! Didn't expect such a quick response. Thank you.

I ran v1.1.1 but no change. I still do not see a diagram.
I am new to Docsify, I would try and debug but I am not sure how.
This is my index.html body.

``` html
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {
      name: 'Avicom: SRSS Mission Audio System',
      repo: '',
      loadSidebar: true,
      subMaxLevel: 2,
      disqus: 'shortname'
    }
  </script>
  <script src="//unpkg.com/docsify/lib/docsify.min.js"></script>
    <!-- plugins -->
  <script src="//unpkg.com/docsify-plantuml@1.1.1/dist/docsify-plantuml.min.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/search.min.js"></script>
  <script src="//unpkg.com/docsify/lib/plugins/zoom-image.min.js"></script>
</body>
```

Should I be installing any packages locally via npm ?

**Comment by imyelo** [comment] 2018-04-06 03:38
It's kind of weird. Two questions need to be confirmed:

1. Is the raw plantuml code still on your page? If the plugin starts working, the raw should disappear.
2. If it disappears, you can verify [here](http://www.plantuml.com/plantuml/) that your code is written correctly and can be parsed properly. 

In addition, can you send the content of your md file which contains the plantuml code and encounters the exception here? This will help me to recurrence issue and identify the cause. 😉

**Comment by AceTheWiz** [comment] 2018-04-06 17:26
Answer
1. Yes
This is the actual output on the rendered site.

@startuml Alice -> Bob: Authentication Request Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request Alice <-- Bob: another authentication Response @enduml

Code is as per example

```
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```
This code checks out ok on www.plantuml.com/plantuml/uml

**Comment by imyelo** [comment] 2018-04-06 18:46
@AceTheWiz 

Yes, this use case works very well with me.
I just put the minimum use case above on [now.sh](https://docsify-plantuml-issue-3-fvsepiepms.now.sh/) .and it seems to be great on my computer (Mac OS 10.13.1, Chrome 65.0.3325.181). How is it working on your side?

Demo: https://docsify-plantuml-issue-3-fvsepiepms.now.sh/
Source: https://docsify-plantuml-issue-3-fvsepiepms.now.sh/_src

**Comment by AceTheWiz** [comment] 2018-04-07 11:11
Aha ! It works and I see where I was going wrong.
I was missing the the **Mardown Code Block** with the "plantuml" qualifier because I used your example (docsify-plantuml/example/README.md) as is. 

If I may suggest that you update your example file to include the Code Block. i.e.
````
```plantuml
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```
````
Thank you very much for your time.

BTW: Have you used **docfx** at all and if so how would you compare it to **docsify** ?

**Comment by imyelo** [comment] 2018-04-07 14:10
Oh I see, the rendered example is really confusing. I should point to the raw one in the document.

As for DocFX, I haven't used it before. I've just read its documentation, and the biggest difference from docsify should be that it automatically generates documents from the project's source code, while docsify uses purely handwritten Markdown files. 

Docsify works so well in its field that you don't even have to prepare any complex programming environment. Not even **Node.js**. **docsify-cli** 's ``serve`` command actually helps you run a static file server.

But docsify is not that convenient if you need to write an API document. In this case, I suggest you try these tools as well: 

- https://github.com/apiaryio/api-blueprint. 
- https://github.com/danielgtaylor/aglio. 
- https://github.com/swagger-api/swagger-ui

However, what suits you is the best tool. 😄

**Comment by imyelo** [comment] 2018-04-07 16:41
I'm closing this issue. Free feel to reopen it if any more questions.

**Closed by imyelo** 2018-04-07 16:41 UTC
